### ISSUE TITLE
Build errors with `lux-lib`

### ISSUE THREAD

**Issue by joshcangit** [nvim-neorocks/lux#708]
I tried building `lux-cli` in both Ubuntu 24.04 and Termux.
I've tried with and without `vendored-lua`.

It still gives the same error regardless.
```
error[E0599]: no method named `include_dir` found for struct `luajit_src::Artifacts` in the current scope
   --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:112:27
    |
112 |                     build.include_dir().to_path_buf(),
    |                           ^^^^^^^^^^^ method not found in `Artifacts`

error[E0599]: no method named `host` found for mutable reference `&mut lua_src::Build` in the current scope
   --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:119:22
    |
117 |                   let build = lua_src::Build::new()
    |  _____________________________-
118 | |                     .target(target)
119 | |                     .host(host_operating_system)
    | |                     -^^^^ method not found in `&mut Build`
    | |_____________________|
    |

error[E0308]: mismatched types
   --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:145:13
    |
145 |             lib_dir,
    |             ^^^^^^^ expected `PathBuf`, found `Path`
    |
help: try using a conversion method
    |
145 |             lib_dir: lib_dir.to_path_buf(),
    |             ++++++++        ++++++++++++++

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `lux-lib` (lib) due to 3 previous errors
```

**Comment by kuator** [comment]
> I tried building `lux-cli` in both Ubuntu 24.04 and Termux. I've tried with and without `vendored-lua`.
> 
> It still gives the same error regardless.
> 
> (On Termux)
> 
> ```
> error[E0599]: no method named `include_dir` found for struct `luajit_src::Artifacts` in the current scope
>    --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:112:27
>     |
> 112 |                     build.include_dir().to_path_buf(),
>     |                           ^^^^^^^^^^^ method not found in `Artifacts`
> 
> error[E0599]: no method named `host` found for mutable reference `&mut lua_src::Build` in the current scope
>    --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:119:22
>     |
> 117 |                   let build = lua_src::Build::new()
>     |  _____________________________-
> 118 | |                     .target(target)
> 119 | |                     .host(host_operating_system)
>     | |                     -^^^^ method not found in `&mut Build`
>     | |_____________________|
>     |
> 
> error[E0308]: mismatched types
>    --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lux-lib-0.6.1/src/lua_installation/mod.rs:145:13
>     |
> 145 |             lib_dir,
>     |             ^^^^^^^ expected `PathBuf`, found `Path`
>     |
> help: try using a conversion method
>     |
> 145 |             lib_dir: lib_dir.to_path_buf(),
>     |             ++++++++        ++++++++++++++
> 
> Some errors have detailed explanations: E0308, E0599.
> For more information about an error, try `rustc --explain E0308`.
> error: could not compile `lux-lib` (lib) due to 3 previous errors
> ```
> 
> (On Ubuntu)
> 
> > I'm gonna run later to catch that later.

Have you installed all the dependencies? https://github.com/nvim-neorocks/lux/issues/700

**Comment by mrcjkb** [comment]
The error messages are about the `luajit-src` dependency, which should be locked to a specific version in the `Cargo.lock`.

It's caused by https://github.com/mlua-rs/luajit-src-rs/commit/1154cf407b2871192e4f91b8ab98531c1ee641f8.

Perhaps you're using an outdated toolchain that is somehow ignoring the lockfile?

**Comment by joshcangit** [comment]
> Have you installed all the dependencies? [#700](https://github.com/nvim-neorocks/lux/issues/700)

Well, I did remember to install `libluajit-5.1-dev` last time.
```
Listing... Done
libluajit-5.1-dev/noble,now 2.1.0+git20231223.c525bcb+dfsg-1 amd64 [installed]
```

But that was last time when I had an issue with `mlua` something.
That was when I was installing `0.3.10` for `lux-cli`.

**Comment by mrcjkb** [comment]
@joshcangit regardless of whether you're building with vendored-lua or not, the problem is that your toolchain is ignoring the `Cargo.lock`, in which we have luajit-src pinned: https://github.com/nvim-neorocks/lux/blob/ec72301d18d8196c62034a1465386d814d357f1e/Cargo.lock#L2186

When we update the luajit-src dependency, we'll have to change the code that is failing to compile for you.
But as long as your toolchain is ignoring the lockfile, you're probably going to run into other errors.

Conveting this to a discussion.
